apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-cont
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env"]
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          name: mymap
          key: special.how
  restartPolicy: Never 
